export const NATIVE_MENU_COMMAND_EVENT = 'guanmo:menu-command'

export type NativeMenuCommand =
  | 'file.new'
  | 'file.open'
  | 'file.save'
  | 'file.close-tab'
  | 'file.export-html'
  | 'edit.undo'
  | 'edit.redo'
  | 'edit.find'
  | 'view.command-palette'
  | 'view.toggle-sidebar'
  | 'view.toggle-ai'
  | 'view.toggle-preview'
  | 'view.toggle-fullscreen'
  | 'app.settings'
  | 'help.product-tour'
  | 'help.feature-intro'
