<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { eventMarker } from '@/services/eventMarker'

type DiffLine = { type: 'same' | 'added' | 'removed'; oldLine?: number; newLine?: number; text: string }
const { t } = useI18n()
const props = withDefaults(defineProps<{ original: string; current: string; fontSize: number; lineHeight: number; fontFamily: string; wordWrap: boolean; lineNumbers: boolean; documentKey?: string; resource?: 'diff' }>(), { documentKey: undefined, resource: 'diff' })
function buildLineDiff(original: string, current: string): DiffLine[] { const a = original.split(/\r?\n/), b = current.split(/\r?\n/), dp = Array.from({ length: a.length + 1 }, () => Array<number>(b.length + 1).fill(0)); for (let i = a.length - 1; i >= 0; i--) for (let j = b.length - 1; j >= 0; j--) dp[i][j] = a[i] === b[j] ? dp[i + 1][j + 1] + 1 : Math.max(dp[i + 1][j], dp[i][j + 1]); const lines: DiffLine[] = []; let i = 0, j = 0; while (i < a.length && j < b.length) { if (a[i] === b[j]) { lines.push({ type: 'same', oldLine: i + 1, newLine: j + 1, text: a[i] }); i++; j++ } else if (dp[i + 1][j] >= dp[i][j + 1]) { lines.push({ type: 'removed', oldLine: i + 1, text: a[i++] }) } else lines.push({ type: 'added', newLine: j + 1, text: b[j++] }) } while (i < a.length) lines.push({ type: 'removed', oldLine: i + 1, text: a[i++] }); while (j < b.length) lines.push({ type: 'added', newLine: j + 1, text: b[j++] }); return lines }
const lines = computed(() => buildLineDiff(props.original, props.current)); const changed = computed(() => lines.value.filter((line) => line.type !== 'same').length)
onMounted(() => eventMarker.mark('diff-create', { documentKey: props.documentKey, resource: props.resource })); onBeforeUnmount(() => eventMarker.mark('diff-dispose', { documentKey: props.documentKey, resource: props.resource }))
</script>
<template><div class="gm-vue-markdown-diff" :style="{ fontSize: `${fontSize}px`, lineHeight, fontFamily }"><header><strong>{{ t('markdownDiff.title') }}</strong><span>{{ t('markdownDiff.changedLines', { count: changed }) }}</span></header><div v-if="!changed" class="gm-vue-markdown-diff__empty">{{ t('markdownDiff.noChanges') }}</div><div v-else><div v-for="(line, index) in lines" :key="`${index}-${line.type}`" class="gm-vue-markdown-diff__line" :class="`gm-vue-markdown-diff__line--${line.type}`" :style="{ gridTemplateColumns: lineNumbers ? '56px 56px 24px minmax(0, 1fr)' : '24px minmax(0, 1fr)' }"><template v-if="lineNumbers"><span>{{ line.oldLine ?? '' }}</span><span>{{ line.newLine ?? '' }}</span></template><i>{{ line.type === 'added' ? '+' : line.type === 'removed' ? '-' : '' }}</i><code :class="{ 'gm-vue-markdown-diff__code--wrap': wordWrap }">{{ line.text || ' ' }}</code></div></div></div></template>
<style scoped>.gm-vue-markdown-diff { height: 100%; min-width: 0; flex: 1; overflow: auto; background: var(--gm-surface); }.gm-vue-markdown-diff header { position: sticky; top: 0; z-index: 1; display: flex; justify-content: space-between; padding: 8px 16px; color: var(--gm-text); background: color-mix(in srgb, var(--gm-surface) 95%, transparent); border-bottom: 1px solid var(--gm-border-subtle); font-family: inherit; font-size: 12px; }.gm-vue-markdown-diff header span { color: var(--gm-text-tertiary); font-size: 11px; }.gm-vue-markdown-diff__empty { padding: 32px 16px; color: var(--gm-text-tertiary); font-family: sans-serif; font-size: 12px; text-align: center; }.gm-vue-markdown-diff__line { display: grid; border-bottom: 1px solid var(--gm-border-subtle); }.gm-vue-markdown-diff__line--added { background: color-mix(in srgb, var(--gm-success) 10%, transparent); }.gm-vue-markdown-diff__line--removed { background: color-mix(in srgb, var(--gm-danger) 10%, transparent); }.gm-vue-markdown-diff__line span,.gm-vue-markdown-diff__line i { padding: 0 6px; color: var(--gm-text-disabled); font-style: normal; text-align: right; user-select: none; }.gm-vue-markdown-diff__line--added i { color: var(--gm-success); }.gm-vue-markdown-diff__line--removed i { color: var(--gm-danger); }.gm-vue-markdown-diff code { padding-left: 8px; color: var(--gm-text); font-family: inherit; white-space: pre; }.gm-vue-markdown-diff__code--wrap { white-space: pre-wrap; overflow-wrap: anywhere; }</style>
