<script setup lang="ts">
import { computed, h, onBeforeUnmount, onMounted, ref, watch, type VNode } from 'vue'
import { remark } from 'remark'
import remarkGfm from 'remark-gfm'
import { createMarkdownPreviewModel, type PreviewBlock } from '@/services/markdownPreviewModel'
import VueInlineMarkdownBlockEditor from './VueInlineMarkdownBlockEditor.vue'

interface Node { type: string; value?: string; url?: string; title?: string; alt?: string; lang?: string | null; depth?: number; ordered?: boolean; start?: number; checked?: boolean | null; position?: { start?: { line?: number } }; children?: Node[] }
interface CommitRequest { block: PreviewBlock; draft: string; documentKey: string; documentVersion: number | string }
type CommitResult = { status: 'applied'; content?: string } | { status: 'conflict'; currentSource: string }
interface ActiveEdit { block: PreviewBlock; snapshot: string; conflict: boolean }
const props = withDefaults(defineProps<{ content: string; fontSize: number; lineHeight: number; fontFamily: string; wordWrap: boolean; documentKey?: string; documentVersion?: number | string; inlineEditEnabled?: boolean; onBlockCommit?: (request: CommitRequest) => Promise<CommitResult> | CommitResult; onHeadingClick?: (line: number) => void; onTaskToggle?: (line: number, checked: boolean) => void }>(), { documentKey: undefined, documentVersion: 0, inlineEditEnabled: false, onBlockCommit: undefined, onHeadingClick: undefined, onTaskToggle: undefined })
const parser = remark().use(remarkGfm), activeEdit = ref<ActiveEdit | null>(null), draft = ref('')
const displayed = computed(() => activeEdit.value?.snapshot ?? props.content)
const model = computed(() => createMarkdownPreviewModel(displayed.value))
const ast = computed(() => parser.parse(displayed.value) as unknown as { children: Node[] })
type Renderable = VNode | string
function editAt(line: number, event: PointerEvent): void { if (!event.altKey || !props.inlineEditEnabled || !props.documentKey || !props.onBlockCommit) return; event.preventDefault(); const block = model.value.blocks.find((item) => line >= item.startLine && line <= item.endLine); if (!block) return; activeEdit.value = { block, snapshot: displayed.value, conflict: false }; draft.value = block.rawSource }
function attrs(node: Node): Record<string, unknown> { const line = node.position?.start?.line ?? 1; return { 'data-md-line': line, onPointerup: (event: PointerEvent) => editAt(line, event) } }
function children(nodes: Node[] = []): Renderable[] { return nodes.flatMap(render) }
function render(node: Node): Renderable[] { const content = children(node.children), line = node.position?.start?.line ?? 1, common = attrs(node); switch (node.type) { case 'text': return [node.value ?? '']; case 'paragraph': return [h('p', common, content)]; case 'heading': return [h(`h${Math.min(6, Math.max(1, node.depth || 2))}`, { ...common, tabindex: props.onHeadingClick ? 0 : undefined, onClick: () => props.onHeadingClick?.(line), onKeydown: (event: KeyboardEvent) => { if (event.key === 'Enter') props.onHeadingClick?.(line) } }, content)]; case 'strong': return [h('strong', content)]; case 'emphasis': return [h('em', content)]; case 'delete': return [h('del', content)]; case 'inlineCode': return [h('code', node.value ?? '')]; case 'code': return [h('pre', { ...common, class: 'gm-vue-markdown-preview__code' }, [h('code', { class: node.lang ? `language-${node.lang}` : undefined }, node.value ?? '')])]; case 'blockquote': return [h('blockquote', common, content)]; case 'list': return [h(node.ordered ? 'ol' : 'ul', { ...common, start: node.start }, content)]; case 'listItem': return [h('li', { ...common, class: node.checked === null || node.checked === undefined ? undefined : 'gm-vue-markdown-preview__task' }, [node.checked === null || node.checked === undefined ? null : h('input', { type: 'checkbox', checked: node.checked, onChange: (event: Event) => props.onTaskToggle?.(line, (event.target as HTMLInputElement).checked) }), ...content])]; case 'link': return [h('a', { href: node.url, title: node.title, target: '_blank', rel: 'noopener noreferrer' }, content)]; case 'image': return [h('img', { ...common, src: node.url, alt: node.alt ?? '', title: node.title })]; case 'break': return [h('br')]; case 'thematicBreak': return [h('hr', common)]; case 'table': return [h('div', { ...common, class: 'gm-vue-markdown-preview__table' }, [h('table', content)])]; case 'tableRow': return [h('tr', content)]; case 'tableCell': return [h('td', content)]; case 'tableHeader': return [h('th', content)]; default: return content } }
const nodes = computed(() => { try { return (ast.value.children ?? []).flatMap(render) } catch { return [displayed.value] } })
async function submit(value: string): Promise<void> { const edit = activeEdit.value; if (!edit || !props.documentKey || !props.onBlockCommit) { activeEdit.value = null; return }; draft.value = value; const result = await props.onBlockCommit({ block: edit.block, draft: value, documentKey: props.documentKey, documentVersion: props.documentVersion }); if (result.status === 'conflict') { activeEdit.value = { ...edit, conflict: true }; return }; activeEdit.value = null }
function outside(event: PointerEvent): void { if (activeEdit.value && !(event.target instanceof Element && event.target.closest('.gm-inline-markdown-editor'))) void submit(draft.value) }
watch(() => props.content, (next) => { if (activeEdit.value && next !== activeEdit.value.snapshot) activeEdit.value = { ...activeEdit.value, conflict: true } })
onMounted(() => document.addEventListener('pointerdown', outside, true)); onBeforeUnmount(() => document.removeEventListener('pointerdown', outside, true))
const RenderContent = () => h('article', { class: 'gm-vue-markdown-preview', style: { fontSize: `${props.fontSize}px`, lineHeight: props.lineHeight, fontFamily: props.fontFamily, whiteSpace: props.wordWrap ? 'normal' : 'pre-wrap' } }, [...nodes.value, activeEdit.value ? h(VueInlineMarkdownBlockEditor, { block: activeEdit.value.block, initialCursor: activeEdit.value.block.rawSource.length, fontSize: props.fontSize, lineHeight: props.lineHeight, fontFamily: props.fontFamily, wordWrap: props.wordWrap, conflict: activeEdit.value.conflict, onDraftChange: (value: string) => { draft.value = value }, onSubmit: (value: string) => void submit(value), onCopyDraft: (value: string) => void navigator.clipboard?.writeText(value) }) : null])
</script>
<template><RenderContent /></template>
<style scoped>
.gm-vue-markdown-preview { min-width: 0; color: var(--gm-text); overflow-wrap: anywhere; }.gm-vue-markdown-preview :deep(h1),.gm-vue-markdown-preview :deep(h2),.gm-vue-markdown-preview :deep(h3),.gm-vue-markdown-preview :deep(h4),.gm-vue-markdown-preview :deep(h5),.gm-vue-markdown-preview :deep(h6) { margin: 1.3em 0 .55em; color: var(--gm-text); line-height: 1.25; }.gm-vue-markdown-preview :deep(h1[tabindex]) { cursor: pointer; }.gm-vue-markdown-preview :deep([data-md-line]) { scroll-margin-top: 24px; }.gm-vue-markdown-preview :deep(p) { margin: .7em 0; }.gm-vue-markdown-preview :deep(a) { color: var(--gm-primary); }.gm-vue-markdown-preview :deep(blockquote) { margin: 1em 0; padding-left: 12px; border-left: 3px solid var(--gm-primary); color: var(--gm-text-secondary); }.gm-vue-markdown-preview :deep(pre) { margin: .9em 0; padding: 12px; overflow: auto; border: 1px solid var(--gm-border); border-radius: var(--gm-radius-md); background: var(--gm-canvas); }.gm-vue-markdown-preview :deep(code) { font-family: var(--gm-font-mono); font-size: .9em; }.gm-vue-markdown-preview :deep(p code) { padding: 1px 4px; border-radius: var(--gm-radius-sm); background: var(--gm-canvas); }.gm-vue-markdown-preview :deep(img) { max-width: 100%; border-radius: var(--gm-radius-md); }.gm-vue-markdown-preview :deep(.gm-vue-markdown-preview__task) { list-style: none; }.gm-vue-markdown-preview :deep(.gm-vue-markdown-preview__task input) { margin-right: 7px; accent-color: var(--gm-primary); }.gm-vue-markdown-preview__table { overflow-x: auto; border: 1px solid var(--gm-border); border-radius: var(--gm-radius-md); }.gm-vue-markdown-preview :deep(table) { width: 100%; border-collapse: collapse; }.gm-vue-markdown-preview :deep(th),.gm-vue-markdown-preview :deep(td) { padding: 6px 8px; border-bottom: 1px solid var(--gm-border-subtle); text-align: left; vertical-align: top; }
</style>
