<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { ChevronLeft, ChevronRight } from 'lucide-vue-next'
import type { TocItem } from '@/services/markdownToc'

type Section = { key: string; title: string; toc: TocItem[]; onHeadingClick: (item: TocItem) => void; emptyText?: string; activeHeading?: string | null }
const { t } = useI18n()
const props = defineProps<{ toc?: TocItem[]; collapsed: boolean; onToggle: () => void; onHeadingClick?: (item: TocItem) => void; sections?: Section[]; activeHeading?: string | null }>()
const visibleSections = computed<Section[]>(() => props.sections?.length ? props.sections.slice(0, 2) : (props.toc?.length ?? 0) > 1 ? [{ key: 'toc', title: t('markdownToc.title'), toc: props.toc ?? [], onHeadingClick: props.onHeadingClick ?? (() => {}) }] : [])
</script>
<template>
  <aside v-if="visibleSections.length" class="gm-vue-markdown-toc" :class="{ 'gm-vue-markdown-toc--collapsed': collapsed, 'gm-vue-markdown-toc--dual': visibleSections.length > 1 }">
    <button type="button" :title="collapsed ? t('markdownToc.expand') : t('markdownToc.collapse')" :aria-label="collapsed ? t('markdownToc.expand') : t('markdownToc.collapse')" :aria-expanded="!collapsed" @click="onToggle"><ChevronLeft v-if="collapsed" :size="13" aria-hidden="true" /><ChevronRight v-else :size="13" aria-hidden="true" /></button>
    <nav v-if="!collapsed" :aria-label="t('markdownToc.ariaLabel')"><section v-for="section in visibleSections" :key="section.key"><strong :title="section.title">{{ section.title }}</strong><div v-if="section.toc.length > 1"><button v-for="item in section.toc" :key="`${section.key}-${item.id}-${item.line}`" type="button" :class="{ 'gm-vue-markdown-toc__item--active': (section.activeHeading ?? activeHeading) === item.id }" :style="{ paddingLeft: `${6 + Math.max(0, item.level - 1) * 10}px` }" :title="t('markdownToc.lineTitle', { text: item.text, line: item.line })" @click="section.onHeadingClick(item)">{{ item.text }}</button></div><p v-else>{{ section.emptyText ?? t('markdownToc.empty') }}</p></section></nav>
  </aside>
</template>
<style scoped>
.gm-vue-markdown-toc { position: relative; display: flex; height: 100%; flex: 0 0 auto; width: 210px; background: var(--gm-surface); border-left: 1px solid var(--gm-border-subtle); }.gm-vue-markdown-toc--collapsed { width: 0; border-left: 0; }.gm-vue-markdown-toc > button { position: absolute; top: 50%; left: 0; z-index: 2; display: grid; width: 20px; height: 48px; place-items: center; color: var(--gm-text-tertiary); background: var(--gm-surface); border: 1px solid var(--gm-border); border-right: 0; border-radius: var(--gm-radius-lg) 0 0 var(--gm-radius-lg); box-shadow: var(--gm-shadow-sm); cursor: pointer; transform: translate(-100%, -50%); }.gm-vue-markdown-toc > button:hover { color: var(--gm-primary); background: var(--gm-surface-hover); }.gm-vue-markdown-toc nav { display: grid; width: 100%; gap: 12px; padding: 12px 16px; overflow-y: auto; color: var(--gm-text-tertiary); font-size: 11px; }.gm-vue-markdown-toc--dual nav { grid-template-columns: repeat(2, minmax(0, 1fr)); overflow: hidden; }.gm-vue-markdown-toc section { min-width: 0; }.gm-vue-markdown-toc--dual section { min-height: 0; overflow-y: auto; }.gm-vue-markdown-toc strong { display: block; margin-bottom: 8px; overflow: hidden; color: var(--gm-text-secondary); text-overflow: ellipsis; white-space: nowrap; }.gm-vue-markdown-toc section > div { display: grid; gap: 2px; }.gm-vue-markdown-toc section button { width: 100%; padding-top: 4px; padding-right: 4px; padding-bottom: 4px; overflow: hidden; color: inherit; text-align: left; text-overflow: ellipsis; white-space: nowrap; background: transparent; border: 0; border-radius: var(--gm-radius-sm); cursor: pointer; }.gm-vue-markdown-toc section button:hover { color: var(--gm-primary); background: var(--gm-surface-hover); }.gm-vue-markdown-toc__item--active { color: var(--gm-active-indicator) !important; background: color-mix(in srgb, var(--gm-active-indicator) 10%, transparent) !important; font-weight: 700; }.gm-vue-markdown-toc p { margin: 0; padding: 8px; color: var(--gm-text-muted); border: 1px dashed var(--gm-border-subtle); border-radius: var(--gm-radius-sm); }
</style>
