<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { ChevronDown, ChevronUp, X } from 'lucide-vue-next'
import { Decoration, EditorView } from '@codemirror/view'
import { StateEffect, StateField, type Range } from '@codemirror/state'
import { findNearestMatchIndex } from '@/services/editorSearch'

type PreviewSource = { content: string; paneRef: { current: HTMLDivElement | null }; previewRef: { current: { scrollToOffset: (offset: number) => void; setSearchState?: (state: { query: string; activeOffset?: number } | null) => void; searchVisible?: (query: string) => Array<{ from: number; to: number }>; getViewportOffset?: () => number | undefined } | null } }
const props = withDefaults(defineProps<{ onClose: () => void; editorViewRef?: { current: EditorView | null }; previewSources?: PreviewSource[] }>(), { editorViewRef: undefined, previewSources: () => [] })
const { t } = useI18n()
const mark = Decoration.mark({ class: 'cm-searchMatch' }), active = Decoration.mark({ class: 'cm-searchMatch-selected' })
const setQueryEffect = StateEffect.define<{ current: number; matches: Array<{ from: number; to: number }> }>()
const clearEffect = StateEffect.define<void>()
const field = StateField.define({ create: () => Decoration.none, update: (deco, tr) => { for (const effect of tr.effects) { if (effect.is(setQueryEffect)) return Decoration.set(effect.value.matches.map((item, index) => (index === effect.value.current ? active : mark).range(item.from, item.to)).sort((a: Range<Decoration>, b: Range<Decoration>) => a.from - b.from)); if (effect.is(clearEffect)) return Decoration.none } return deco.map(tr.changes) }, provide: (item) => EditorView.decorations.from(item) })
const query = ref(''), replaceText = ref(''), matchCount = ref(0), currentMatch = ref(0), input = ref<HTMLInputElement | null>(null); let matches: Array<{ from: number; to: number }> = []; let previewMatches: Array<{ sourceIndex: number; from: number; to: number }> = []
const isEditor = () => Boolean(props.editorViewRef)
function find(content: string, value: string): Array<{ from: number; to: number }> { if (!value) return []; const re = new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi'), found = []; let match: RegExpExecArray | null; while ((match = re.exec(content))) found.push({ from: match.index, to: match.index + match[0].length }); return found }
function nearest(items: Array<{ from: number; to: number }>, anchor?: number): number { return findNearestMatchIndex(items, anchor) }
function syncPreview(value: string, sourceIndex: number, offset?: number): void { props.previewSources.forEach((source, index) => source.previewRef.current?.setSearchState?.(value ? (index === sourceIndex && offset !== undefined ? { query: value, activeOffset: offset } : { query: value }) : null)) }
function reveal(item: { sourceIndex: number; from: number }, value: string): void { syncPreview(value, item.sourceIndex, item.from); props.previewSources[item.sourceIndex]?.previewRef.current?.scrollToOffset(item.from) }
function search(value: string): void { query.value = value; if (isEditor()) { const view = props.editorViewRef?.current; if (!view) return; if (!view.state.field(field, false)) view.dispatch({ effects: StateEffect.appendConfig.of(field) }); matches = find(view.state.doc.toString(), value); currentMatch.value = nearest(matches, view.state.selection.main.head); matchCount.value = matches.length; if (matches.length) view.dispatch({ selection: { anchor: matches[currentMatch.value].from, head: matches[currentMatch.value].to }, effects: setQueryEffect.of({ current: currentMatch.value, matches }), scrollIntoView: true }); else view.dispatch({ effects: clearEffect.of() }); return } previewMatches = props.previewSources.flatMap((source, sourceIndex) => (source.previewRef.current?.searchVisible?.(value) ?? find(source.content, value)).map((item) => ({ ...item, sourceIndex }))); currentMatch.value = nearest(previewMatches, props.previewSources[0]?.previewRef.current?.getViewportOffset?.()); matchCount.value = previewMatches.length; if (value && previewMatches[currentMatch.value]) reveal(previewMatches[currentMatch.value], value); else syncPreview(value, -1) }
function navigate(direction: 1 | -1): void { if (!query.value || !matchCount.value) return; currentMatch.value = (currentMatch.value + direction + matchCount.value) % matchCount.value; if (isEditor()) { const view = props.editorViewRef?.current, item = matches[currentMatch.value]; if (view && item) view.dispatch({ selection: { anchor: item.from, head: item.to }, effects: setQueryEffect.of({ current: currentMatch.value, matches }), scrollIntoView: true }) } else { const item = previewMatches[currentMatch.value]; if (item) reveal(item, query.value) } }
function replace(): void { const view = props.editorViewRef?.current; if (!view || !query.value) return; const selection = view.state.selection.main; if (view.state.sliceDoc(selection.from, selection.to).toLowerCase() === query.value.toLowerCase()) view.dispatch({ changes: { from: selection.from, to: selection.to, insert: replaceText.value } }); navigate(1) }
function replaceAll(): void { const view = props.editorViewRef?.current; if (!view || !query.value) return; const doc = view.state.doc.toString(), replaced = doc.replace(new RegExp(query.value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi'), replaceText.value); if (doc !== replaced) view.dispatch({ changes: { from: 0, to: doc.length, insert: replaced } }); search(query.value) }
function keydown(event: KeyboardEvent): void { if (event.key === 'Escape') { event.preventDefault(); props.onClose() } else if (event.key === 'Enter') { event.preventDefault(); navigate(event.shiftKey ? -1 : 1) } }
onMounted(async () => { const view = props.editorViewRef?.current; if (view && !view.state.field(field, false)) view.dispatch({ effects: StateEffect.appendConfig.of(field) }); window.addEventListener('keydown', keydown, true); await nextTick(); input.value?.focus() }); onBeforeUnmount(() => { window.removeEventListener('keydown', keydown, true); const view = props.editorViewRef?.current; if (view?.state.field(field, false)) view.dispatch({ effects: clearEffect.of() }); syncPreview('', -1) })
</script>
<template><div data-editor-search-overlay class="gm-vue-search-overlay"><div><input ref="input" :value="query" :placeholder="t('searchOverlay.search')" @input="search(($event.target as HTMLInputElement).value)" @keydown="keydown" /><button type="button" :title="t('searchOverlay.previous')" @click="navigate(-1)"><ChevronUp :size="15" /></button><button type="button" :title="t('searchOverlay.next')" @click="navigate(1)"><ChevronDown :size="15" /></button><span v-if="query">{{ matchCount ? `${currentMatch + 1}/${matchCount}` : t('searchOverlay.none') }}</span><button type="button" :title="t('searchOverlay.close')" @click="onClose"><X :size="15" /></button></div><div v-if="isEditor()"><input v-model="replaceText" :placeholder="t('searchOverlay.replace')" /><button type="button" @click="replace">{{ t('searchOverlay.replaceOne') }}</button><button type="button" @click="replaceAll">{{ t('searchOverlay.replaceAll') }}</button></div></div></template>
<style scoped>.gm-vue-search-overlay{position:absolute;top:8px;right:8px;z-index:50;min-width:300px;padding:12px;background:var(--gm-surface);border:1px solid var(--gm-border);border-radius:var(--gm-radius-lg);box-shadow:var(--gm-shadow-lg)}.gm-vue-search-overlay>div{display:flex;gap:8px;align-items:center}.gm-vue-search-overlay>div+div{margin-top:8px}.gm-vue-search-overlay input{min-width:0;flex:1;height:32px;padding:0 10px;color:var(--gm-text);background:var(--gm-canvas);border:1px solid var(--gm-border);border-radius:var(--gm-radius-sm);outline:0}.gm-vue-search-overlay button{display:grid;padding:6px;place-items:center;color:var(--gm-text-secondary);background:var(--gm-surface-hover);border:0;border-radius:var(--gm-radius-sm);cursor:pointer;font-size:11px}.gm-vue-search-overlay button:hover{color:var(--gm-text);background:var(--gm-surface-overlay)}.gm-vue-search-overlay span{min-width:40px;color:var(--gm-text-tertiary);font-size:11px;text-align:center}</style>
