<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { getVersion } from '@tauri-apps/api/app'
import { useVuePerfMonitor } from '@/composables/useVuePerfMonitor'
import { saveFileDialog, writeFile } from '@/hooks/useTauri'
import { eventMarker, type PerfEvent } from '@/services/eventMarker'
import { PERF_SCHEMA_VERSION, withLegacyPerfFields, type PerfData } from '@/services/perfTypes'
import { getPerfHistory, usePerfStore, type SampleIntervalMs } from '@/stores/perfStore'
import { useSettingsStore } from '@/stores/settingsStore'
import { toast } from '@/services/toast'
import { useZustandSelector } from '@/composables/useZustandSelector'

type Section = 'overview' | 'processes' | 'resources' | 'context' | 'events'
const { t } = useI18n()
const section = ref<Section>('overview')
const current = useZustandSelector(usePerfStore, (state) => state.current)
const events = useZustandSelector(usePerfStore, (state) => state.events)
const baseline = useZustandSelector(usePerfStore, (state) => state.baseline)
const peaks = useZustandSelector(usePerfStore, (state) => state.testPeaks)
const settings = useZustandSelector(usePerfStore, (state) => state.settings)
const collapsed = useZustandSelector(usePerfStore, (state) => state.isCollapsed)
const paused = useZustandSelector(usePerfStore, (state) => state.isPaused)
useVuePerfMonitor()

const EMPTY = { timestamp: 0, appWorkingSetKb: 0, appPrivateWorkingSetKb: 0, appPrivateBytesKb: 0, webviewWorkingSetKb: 0, webviewPrivateWorkingSetKb: 0, webviewPrivateBytesKb: 0, rustWorkingSetKb: 0, rustPrivateWorkingSetKb: 0, rustPrivateBytesKb: 0, webviewProcessCount: 0, rendererProcessCount: 0, gpuProcessCount: 0, utilityProcessCount: 0, cpuPercent: 0, cpuNormalizedPercent: 0, cpuCoreEquivalent: 0, systemCpuPercent: 0, processBreakdown: [], fps: 0, jsHeapUsedMb: 0, jsHeapTotalMb: 0, domNodeCount: 0, detachedDomNodes: 0, activeTimeoutCount: 0, activeIntervalCount: 0, activeRafCount: 0, eventListenerCount: 0, eventListenerWindowCount: 0, eventListenerDocumentCount: 0, eventListenerDomCount: 0, eventListenerUnknownCount: 0, mutationObserverCount: 0, resizeObserverCount: 0, intersectionObserverCount: 0, activeObjectUrlCount: 0, longTaskCount: 0, longTaskTotalDurationMs: 0, longTaskMaxDurationMs: 0, lastLongTaskAt: null, lastLongTaskMode: null, lastLongTaskUserAction: null, monacoModelCount: 0, monacoModelTotalChars: 0, monacoEditorInstanceCount: 0, monacoDiffEditorInstanceCount: 0, monacoDecorationCount: 0, monacoMarkerCount: 0, monacoModels: [], currentMode: 'edit', docCharCount: 0, activeDocumentCount: 0, activeDocumentCharCount: 0, totalOpenDocumentCharCount: 0, activeDocumentLineCount: 0, previewInstanceCount: 0, editorInstanceCount: 0, aiPanelOpen: false, isFullscreen: false, totalCollectDurationMs: 0, processQueryDurationMs: 0, jsMetricDurationMs: 0, storeUpdateDurationMs: 0, panelRenderDurationMs: 0 } satisfies PerfData
const data = computed(() => current.value ?? EMPTY)
const tabs: Array<[Section, string]> = [['overview', t('perfMonitor.overview')], ['processes', t('perfMonitor.processes')], ['resources', t('perfMonitor.resources')], ['context', t('perfMonitor.context')], ['events', t('perfMonitor.events')]]
const overview = computed(() => [[t('perfMonitor.appPrivateMemory'), formatKb(data.value.appPrivateWorkingSetKb)], [t('perfMonitor.webviewPrivateMemory'), formatKb(data.value.webviewPrivateWorkingSetKb)], [t('perfMonitor.rustPrivateMemory'), formatKb(data.value.rustPrivateWorkingSetKb)], [t('perfMonitor.guanmoCpu'), `${data.value.cpuNormalizedPercent.toFixed(1)}%`], [t('perfMonitor.systemCpu'), `${data.value.systemCpuPercent.toFixed(1)}%`], ['FPS', String(data.value.fps)], ['Long Task', `${data.value.longTaskCount} / ${data.value.longTaskMaxDurationMs.toFixed(1)}ms`]])
const resources = computed(() => [['JS Heap', `${data.value.jsHeapUsedMb.toFixed(1)} / ${data.value.jsHeapTotalMb.toFixed(1)} MB`], ['DOM', data.value.domNodeCount], ['Detached DOM', data.value.detachedDomNodes], ['Timeout', data.value.activeTimeoutCount], ['Interval', data.value.activeIntervalCount], ['RAF', data.value.activeRafCount], [t('perfMonitor.listeners'), data.value.eventListenerCount], ['MutationObserver', data.value.mutationObserverCount], ['ResizeObserver', data.value.resizeObserverCount], ['Object URL', data.value.activeObjectUrlCount]])
const context = computed(() => [[t('perfMonitor.activeDocuments'), data.value.activeDocumentCount], [t('perfMonitor.activeDocumentChars'), data.value.activeDocumentCharCount.toLocaleString()], [t('perfMonitor.activeDocumentLines'), data.value.activeDocumentLineCount.toLocaleString()], [t('perfMonitor.totalOpenChars'), data.value.totalOpenDocumentCharCount.toLocaleString()], [t('perfMonitor.previewInstances'), data.value.previewInstanceCount], [t('perfMonitor.editorInstances'), data.value.editorInstanceCount], [t('perfMonitor.mode'), data.value.currentMode], [t('perfMonitor.aiPanel'), data.value.aiPanelOpen ? t('perfMonitor.open') : t('perfMonitor.closed')], [t('perfMonitor.fullscreen'), data.value.isFullscreen ? t('perfMonitor.yes') : t('perfMonitor.no')]])
function formatKb(kb: number): string { return kb >= 1024 * 1024 ? `${(kb / 1024 / 1024).toFixed(2)} GB` : `${(kb / 1024).toFixed(1)} MB` }
function formatTime(timestamp: number): string { return new Date(timestamp).toLocaleTimeString('zh-CN', { hour12: false }) }
function eventLabel(type: PerfEvent['type']): string { return ({ 'app-start': t('perfMonitor.eventAppStart'), 'app-ready': t('perfMonitor.eventAppReady'), 'switch-document': t('perfMonitor.eventSwitchDocument'), 'switch-mode-complete': t('perfMonitor.eventSwitchModeComplete'), 'mode-settled': t('perfMonitor.eventModeSettled'), 'ai-panel-open': t('perfMonitor.eventAiPanelOpen'), 'ai-panel-close': t('perfMonitor.eventAiPanelClose'), 'enter-fullscreen': t('perfMonitor.eventEnterFullscreen'), 'exit-fullscreen': t('perfMonitor.eventExitFullscreen'), 'baseline-set': t('perfMonitor.eventBaselineSet'), 'memory-snapshot': t('perfMonitor.eventMemorySnapshot') } as Partial<Record<PerfEvent['type'], string>>)[type] ?? type }
function setIntervalValue(event: Event): void { usePerfStore.getState().setSampleInterval(Number((event.target as HTMLSelectElement).value) as SampleIntervalMs) }
function setBaseline(kind: 'idle' | 'document'): void { if (!usePerfStore.getState().current) return; usePerfStore.getState().setBaseline(kind); eventMarker.mark('baseline-set', { kind }) }
function safeData(item: PerfData): object { return { ...withLegacyPerfFields(item), lastLongTaskUserAction: item.lastLongTaskUserAction ? '[redacted-action]' : null, monacoModels: item.monacoModels.map((model) => ({ ...model, uri: '[redacted-uri]' })) } }
async function exportReport(): Promise<void> { try { const state = usePerfStore.getState(); const path = await saveFileDialog(`perf-report-${Date.now()}.json`, [{ name: 'JSON', extensions: ['json'] }]); if (!path) return; const report = { schemaVersion: PERF_SCHEMA_VERSION, exportedAt: new Date().toISOString(), environment: { platform: navigator.platform, language: navigator.language }, testContext: { modePerformancePolicy: useSettingsStore.getState().editor.modePerformancePolicy }, appVersion: await getVersion().catch(() => 'unknown'), monitorSettings: state.settings, baseline: state.baseline ? { kind: state.baseline.kind, setAt: state.baseline.setAt, snapshot: safeData(state.baseline.snapshot) } : null, processBreakdown: state.current?.processBreakdown ?? [], events: eventMarker.exportEvents(), history: getPerfHistory().map(safeData) }; await writeFile(path, JSON.stringify(report, null, 2)); toast.success(t('perfMonitor.exported')) } catch (error) { toast.error(error instanceof Error ? t('perfMonitor.exportFailedDetail', { message: error.message }) : t('perfMonitor.exportFailed')) } }
</script>

<template>
  <button v-if="collapsed" type="button" class="gm-vue-perf-trigger" @click="usePerfStore.getState().toggleCollapsed()">{{ t('perfMonitor.trigger') }} {{ formatKb(data.appPrivateWorkingSetKb) }} · {{ data.cpuNormalizedPercent.toFixed(1) }}%</button>
  <section v-else class="gm-vue-perf-panel">
    <header><strong>{{ t('perfMonitor.title') }}</strong><select :aria-label="t('perfMonitor.sampleRate')" :value="settings.sampleIntervalMs" @change="setIntervalValue"><option :value="5000">5s</option><option :value="1000">1s（60秒）</option><option :value="500">500ms（60秒）</option><option :value="250">250ms（60秒）</option></select><button type="button" @click="usePerfStore.getState().togglePaused()">{{ paused ? t('perfMonitor.resume') : t('perfMonitor.pause') }}</button><button type="button" @click="usePerfStore.getState().toggleCollapsed()">{{ t('perfMonitor.collapse') }}</button></header>
    <nav><button v-for="tab in tabs" :key="tab[0]" type="button" :data-active="section === tab[0]" @click="section = tab[0]">{{ tab[1] }}</button></nav>
    <main v-if="section === 'overview'" class="gm-vue-perf-grid"><article v-for="item in overview" :key="item[0]"><span>{{ item[0] }}</span><b>{{ item[1] }}</b></article><p class="gm-vue-perf-overhead">{{ t('perfMonitor.overhead', { collect: data.totalCollectDurationMs.toFixed(1), process: data.processQueryDurationMs.toFixed(1), js: data.jsMetricDurationMs.toFixed(1), store: data.storeUpdateDurationMs.toFixed(1), panel: data.panelRenderDurationMs.toFixed(1) }) }}</p><p v-if="baseline">{{ t('perfMonitor.baselineLabel', { kind: baseline.kind, time: new Date(baseline.setAt).toLocaleTimeString('zh-CN') }) }}</p></main>
    <main v-else-if="section === 'processes'" class="gm-vue-perf-table"><p>{{ t('perfMonitor.webviewProcesses', { count: data.webviewProcessCount, renderer: data.rendererProcessCount, gpu: data.gpuProcessCount, utility: data.utilityProcessCount }) }}</p><table><thead><tr><th>PID</th><th>{{ t('perfMonitor.type') }}</th><th>{{ t('perfMonitor.privateWs') }}</th><th>CPU</th><th>{{ t('perfMonitor.threads') }}</th></tr></thead><tbody><tr v-for="process in data.processBreakdown.filter((item) => item.processType !== 'rust-main')" :key="process.pid"><td>{{ process.pid }}</td><td>{{ process.processType }}</td><td>{{ formatKb(process.privateWorkingSetKb) }}</td><td>{{ process.cpuPercent.toFixed(1) }}%</td><td>{{ process.threadCount }}</td></tr></tbody></table></main>
    <main v-else-if="section === 'resources' || section === 'context'" class="gm-vue-perf-grid"><article v-for="item in section === 'resources' ? resources : context" :key="item[0]"><span>{{ item[0] }}</span><b>{{ item[1] }}</b></article></main>
    <main v-else class="gm-vue-perf-events"><div v-for="event in [...events].reverse()" :key="event.id"><time>{{ formatTime(event.timestamp) }}</time><b>{{ eventLabel(event.type) }}</b><span>{{ event.durationMs?.toFixed(1) ? `${event.durationMs.toFixed(1)}ms` : '' }}</span></div><p v-if="!events.length">{{ t('perfMonitor.noEvents') }}</p></main>
    <footer><button type="button" @click="setBaseline('idle')">{{ t('perfMonitor.setIdleBaseline') }}</button><button type="button" @click="setBaseline('document')">{{ t('perfMonitor.setDocumentBaseline') }}</button><button type="button" @click="usePerfStore.getState().clearBaseline()">{{ t('perfMonitor.clearBaseline') }}</button><button type="button" @click="usePerfStore.getState().startTest()">{{ t('perfMonitor.startTest') }}</button><button type="button" @click="eventMarker.mark('memory-snapshot'); void exportReport()">{{ t('perfMonitor.exportJson') }}</button><button type="button" class="gm-vue-perf-clear" @click="eventMarker.clearEvents(); usePerfStore.getState().clearHistory()">{{ t('perfMonitor.clearHistory') }}</button></footer>
  </section>
</template>

<style scoped>
.gm-vue-perf-trigger,.gm-vue-perf-panel { position: fixed; z-index: 9999; right: 16px; bottom: 44px; color: #e5e7eb; border: 1px solid #374151; background: rgb(17 24 39 / 95%); box-shadow: var(--gm-shadow-lg); font-family: var(--gm-font-mono); font-size: 12px; }.gm-vue-perf-trigger { padding: 8px 12px; border-radius: var(--gm-radius-sm); }.gm-vue-perf-panel { width: min(760px, calc(100vw - 32px)); overflow: hidden; border-radius: var(--gm-radius-md); }.gm-vue-perf-panel header,.gm-vue-perf-panel footer,.gm-vue-perf-panel nav { display: flex; padding: 8px 12px; align-items: center; gap: 6px; border-bottom: 1px solid #374151; }.gm-vue-perf-panel header strong { margin-right: auto; color: white; }.gm-vue-perf-panel button,.gm-vue-perf-panel select { padding: 4px 8px; color: inherit; border: 0; border-radius: var(--gm-radius-sm); background: #374151; font: inherit; }.gm-vue-perf-panel nav { padding: 0; }.gm-vue-perf-panel nav button { padding: 8px 12px; border-radius: 0; background: transparent; color: #9ca3af; }.gm-vue-perf-panel nav button[data-active='true'] { color: white; box-shadow: inset 0 -2px 0 #60a5fa; }.gm-vue-perf-panel main { max-height: 320px; overflow: auto; }.gm-vue-perf-grid { display: grid; padding: 12px; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 8px; }.gm-vue-perf-grid article { display: grid; gap: 3px; padding: 8px; border: 1px solid #374151; border-radius: var(--gm-radius-sm); background: rgb(31 41 55 / 60%); }.gm-vue-perf-grid article span { color: #9ca3af; font-size: 10px; }.gm-vue-perf-grid article b { color: white; font-size: 13px; font-weight: 500; }.gm-vue-perf-overhead,.gm-vue-perf-grid > p { grid-column: 1 / -1; margin: 0; color: #9ca3af; }.gm-vue-perf-table,.gm-vue-perf-events { padding: 12px; }.gm-vue-perf-table p,.gm-vue-perf-events p { color: #9ca3af; }.gm-vue-perf-table table { width: 100%; border-collapse: collapse; text-align: left; }.gm-vue-perf-table th,.gm-vue-perf-table td { padding: 4px; border-bottom: 1px solid #1f2937; }.gm-vue-perf-table th { position: sticky; top: 0; color: #9ca3af; background: #111827; }.gm-vue-perf-events div { display: grid; padding: 4px 0; grid-template-columns: 70px 150px 1fr; gap: 8px; border-bottom: 1px solid #1f2937; }.gm-vue-perf-events time,.gm-vue-perf-events span { color: #9ca3af; }.gm-vue-perf-panel footer { border-top: 1px solid #374151; border-bottom: 0; }.gm-vue-perf-clear { margin-left: auto; }
</style>
