<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { X } from 'lucide-vue-next'
import { listKnowledgeDocuments, removeKnowledgeDocuments, type KnowledgeDocumentItem } from '@/services/rag/knowledgeBase'
import { useSettingsStore } from '@/stores/settingsStore'
import { useZustandSelector } from '@/composables/useZustandSelector'
import { toast } from '@/services/toast'

const { t } = useI18n()
const props = defineProps<{ open: boolean; onClose: () => void }>()
const STATE_LABELS: Record<string, string> = { PENDING: t('knowledgeBaseManager.statePending'), CHUNKED: t('knowledgeBaseManager.stateChunked'), EMBEDDING: t('knowledgeBaseManager.stateEmbedding'), INDEXED: t('knowledgeBaseManager.stateIndexed'), FAILED: t('knowledgeBaseManager.stateFailed') }
const documents = ref<KnowledgeDocumentItem[]>([]), loading = ref(false), search = ref(''), selected = ref<Set<string>>(new Set()), removing = ref(false), confirmOpen = ref(false), error = ref<string | null>(null), closeButton = ref<HTMLButtonElement | null>(null)
const autoIndexEnabled = useZustandSelector(useSettingsStore, (state) => state.knowledge.autoIndexEnabled)
const filtered = computed(() => { const query = search.value.trim().toLowerCase(); return query ? documents.value.filter((doc) => (doc.title || doc.filePath.split(/[/\\]/).pop() || '').toLowerCase().includes(query)) : documents.value })
const allSelected = computed(() => filtered.value.length > 0 && filtered.value.every((item) => selected.value.has(item.filePath)))
function fileName(doc: KnowledgeDocumentItem): string { return doc.title || doc.filePath.split(/[/\\]/).pop() || doc.filePath }
async function load(): Promise<void> { loading.value = true; error.value = null; try { documents.value = await listKnowledgeDocuments() } catch (cause) { error.value = cause instanceof Error ? cause.message : String(cause) } finally { loading.value = false } }
function close(): void { if (confirmOpen.value) { confirmOpen.value = false; return }; props.onClose() }
function keydown(event: KeyboardEvent): void { if (event.key === 'Escape') close() }
function toggle(path: string): void { const next = new Set(selected.value); next.has(path) ? next.delete(path) : next.add(path); selected.value = next }
function toggleAll(): void { const next = new Set(selected.value); if (allSelected.value) filtered.value.forEach((doc) => next.delete(doc.filePath)); else filtered.value.forEach((doc) => next.add(doc.filePath)); selected.value = next }
async function remove(): Promise<void> { removing.value = true; try { const result = await removeKnowledgeDocuments([...selected.value]); if (result.failed.length) { selected.value = new Set(result.failed.map((item) => item.filePath)); toast.error(t('knowledgeBaseManager.partialFailed', { names: result.failed.map((item) => item.filePath.split(/[/\\]/).pop()).join('、') })) } else { selected.value = new Set(); toast.success(t('knowledgeBaseManager.removed', { count: result.success.length })) }; await load() } catch (cause) { toast.error(cause instanceof Error ? cause.message : t('knowledgeBaseManager.removeFailed')) } finally { removing.value = false; confirmOpen.value = false } }
watch(() => props.open, async (open) => { if (!open) { window.removeEventListener('keydown', keydown); return }; search.value = ''; selected.value = new Set(); confirmOpen.value = false; void load(); window.addEventListener('keydown', keydown); await nextTick(); closeButton.value?.focus() }, { immediate: true })
onBeforeUnmount(() => window.removeEventListener('keydown', keydown))
</script>

<template>
  <div v-if="open" class="gm-vue-kb-scrim" @mousedown.self="close"><section class="gm-vue-kb-dialog" role="dialog" aria-modal="true" aria-labelledby="kb-manager-title"><header><h2 id="kb-manager-title">{{ t('knowledgeBaseManager.title') }}</h2><button ref="closeButton" type="button" :title="t('knowledgeBaseManager.close')" @click="close"><X :size="17" /></button></header><main><input v-model="search" type="search" :placeholder="t('knowledgeBaseManager.searchPlaceholder')" /><p v-if="loading">{{ t('knowledgeBaseManager.loading') }}</p><p v-else-if="error" class="gm-vue-kb-error">{{ t('knowledgeBaseManager.loadFailed', { error }) }}</p><p v-else-if="!filtered.length">{{ search.trim() ? t('knowledgeBaseManager.noMatch') : t('knowledgeBaseManager.empty') }}</p><template v-else><label class="gm-vue-kb-select-all"><input type="checkbox" :checked="allSelected" @change="toggleAll" />{{ t('knowledgeBaseManager.selectAll') }}</label><label v-for="doc in filtered" :key="doc.filePath" class="gm-vue-kb-row"><input type="checkbox" :checked="selected.has(doc.filePath)" @change="toggle(doc.filePath)" /><span><b>{{ fileName(doc) }}</b><small>{{ STATE_LABELS[doc.state] || doc.state }} · {{ doc.filePath }}</small></span></label></template></main><footer><span>{{ t('knowledgeBaseManager.selected', { count: selected.size }) }}</span><button type="button" class="gm-vue-settings-primary" :disabled="!selected.size || removing" @click="confirmOpen = true">{{ removing ? t('knowledgeBaseManager.removing') : t('knowledgeBaseManager.batchRemove') }}</button></footer></section><div v-if="confirmOpen" class="gm-vue-kb-confirm" @mousedown.self="confirmOpen = false"><section><h3>{{ t('knowledgeBaseManager.confirmTitle') }}</h3><p>{{ t('knowledgeBaseManager.confirmDescription', { count: selected.size }) }}</p><p class="gm-vue-kb-error">{{ t('knowledgeBaseManager.confirmHint') }}</p><p v-if="autoIndexEnabled">{{ t('knowledgeBaseManager.autoIndexWarning') }}</p><footer><button type="button" @click="confirmOpen = false">{{ t('knowledgeBaseManager.cancel') }}</button><button type="button" class="gm-vue-settings-primary" :disabled="removing" @click="remove">{{ t('knowledgeBaseManager.confirmRemove') }}</button></footer></section></div></div>
</template>

<style scoped>
.gm-vue-kb-scrim,.gm-vue-kb-confirm { position: fixed; z-index: 1100; inset: 0; display: grid; padding: 20px; place-items: center; background: rgb(0 0 0 / 45%); }.gm-vue-kb-dialog { display: flex; width: min(100%, 640px); max-height: 85vh; flex-direction: column; overflow: hidden; border: 1px solid var(--gm-border); border-radius: var(--gm-radius-lg); background: var(--gm-surface); box-shadow: var(--gm-shadow-lg); }.gm-vue-kb-dialog > header,.gm-vue-kb-dialog > footer { display: flex; padding: 14px 18px; align-items: center; justify-content: space-between; gap: 10px; border-bottom: 1px solid var(--gm-border); }.gm-vue-kb-dialog h2,.gm-vue-kb-confirm h3 { margin: 0; color: var(--gm-text); font-size: var(--gm-text-lg); }.gm-vue-kb-dialog header button { display: grid; width: 32px; height: 32px; place-items: center; color: var(--gm-text-secondary); border: 0; border-radius: var(--gm-radius-sm); background: transparent; }.gm-vue-kb-dialog main { min-height: 0; padding: 14px 18px; overflow: auto; }.gm-vue-kb-dialog main > input { width: 100%; box-sizing: border-box; padding: 8px 10px; color: var(--gm-text); border: 1px solid var(--gm-border); border-radius: var(--gm-radius-sm); background: var(--gm-canvas); }.gm-vue-kb-dialog main > p { padding: 25px; color: var(--gm-text-tertiary); text-align: center; }.gm-vue-kb-select-all,.gm-vue-kb-row { display: flex; padding: 8px; align-items: start; gap: 8px; color: var(--gm-text-secondary); border-bottom: 1px solid var(--gm-border-subtle); font-size: var(--gm-text-sm); }.gm-vue-kb-row:hover { background: var(--gm-surface-elevated); }.gm-vue-kb-row span { display: grid; min-width: 0; gap: 4px; }.gm-vue-kb-row b { overflow: hidden; color: var(--gm-text); text-overflow: ellipsis; white-space: nowrap; }.gm-vue-kb-row small { overflow: hidden; color: var(--gm-text-tertiary); text-overflow: ellipsis; white-space: nowrap; }.gm-vue-kb-dialog > footer { border-top: 1px solid var(--gm-border); border-bottom: 0; color: var(--gm-text-secondary); font-size: var(--gm-text-sm); }.gm-vue-kb-dialog button,.gm-vue-kb-confirm button { padding: 6px 10px; color: var(--gm-text-secondary); border: 1px solid var(--gm-border); border-radius: var(--gm-radius-sm); background: var(--gm-surface); font-size: var(--gm-text-xs); }.gm-vue-kb-confirm { z-index: 1110; background: rgb(0 0 0 / 30%); }.gm-vue-kb-confirm section { width: min(100%, 380px); padding: 18px; border: 1px solid var(--gm-border); border-radius: var(--gm-radius-lg); background: var(--gm-surface); }.gm-vue-kb-confirm p { color: var(--gm-text-secondary); font-size: var(--gm-text-sm); }.gm-vue-kb-confirm footer { display: flex; justify-content: end; gap: 8px; }.gm-vue-kb-error { color: var(--gm-error) !important; }
</style>
