<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import type { ThemeId } from '@/stores/settingsStore'
const { t } = useI18n()
const props = defineProps<{ value: ThemeId; onChange: (value: ThemeId) => void }>()
const options: Array<{ key: ThemeId; label: string; description: string }> = [{ key: 'warm', label: t('themePicker.warm'), description: t('themePicker.warmDescription') }, { key: 'light', label: t('themePicker.light'), description: t('themePicker.lightDescription') }, { key: 'dark', label: t('themePicker.dark'), description: t('themePicker.darkDescription') }, { key: 'paper', label: t('themePicker.paper'), description: t('themePicker.paperDescription') }, { key: 'github-light', label: t('themePicker.githubLight'), description: t('themePicker.githubLightDescription') }]
</script>
<template><div class="gm-vue-theme-picker" role="radiogroup" :aria-label="t('themePicker.label')"><button v-for="option in options" :key="option.key" type="button" :data-preview-theme="option.key" :data-active="value === option.key" role="radio" :aria-checked="value === option.key" @click="onChange(option.key)"><span class="gm-vue-theme-picker__preview"><i /><i /><i /><b /></span><strong>{{ option.label }}</strong><small>{{ option.description }}</small></button></div></template>
<style scoped>.gm-vue-theme-picker { display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); gap: 8px; }.gm-vue-theme-picker button { display: grid; min-width: 0; padding: 6px; gap: 4px; color: var(--gm-text); border: 1px solid var(--gm-border); border-radius: var(--gm-radius-md); background: var(--gm-surface); text-align: left; }.gm-vue-theme-picker button[data-active='true'] { border-color: var(--gm-primary); box-shadow: inset 0 0 0 1px var(--gm-primary); }.gm-vue-theme-picker__preview { display: grid; height: 48px; padding: 8px; gap: 5px; border: 1px solid var(--gm-border-subtle); border-radius: var(--gm-radius-sm); background: var(--gm-canvas); }.gm-vue-theme-picker__preview i { display: block; width: 88%; height: 3px; background: var(--gm-text-tertiary); opacity: .5; }.gm-vue-theme-picker__preview i:nth-child(2) { width: 72%; }.gm-vue-theme-picker__preview i:nth-child(3) { width: 48%; }.gm-vue-theme-picker__preview b { display: block; width: 28%; height: 5px; margin-top: auto; background: var(--gm-primary); }.gm-vue-theme-picker strong { overflow: hidden; font-size: var(--gm-text-xs); text-overflow: ellipsis; white-space: nowrap; }.gm-vue-theme-picker small { min-height: 24px; color: var(--gm-text-tertiary); font-size: 10px; line-height: 1.2; } @media (max-width: 680px) { .gm-vue-theme-picker { grid-template-columns: repeat(2, minmax(0, 1fr)); } }</style>
